/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISushiXSwap,
  ISushiXSwapInterface,
} from "../../../contracts/interfaces/ISushiXSwap";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint8[]",
        name: "actions",
        type: "uint8[]",
      },
      {
        internalType: "uint256[]",
        name: "values",
        type: "uint256[]",
      },
      {
        internalType: "bytes[]",
        name: "datas",
        type: "bytes[]",
      },
    ],
    name: "cook",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class ISushiXSwap__factory {
  static readonly abi = _abi;
  static createInterface(): ISushiXSwapInterface {
    return new utils.Interface(_abi) as ISushiXSwapInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISushiXSwap {
    return new Contract(address, _abi, signerOrProvider) as ISushiXSwap;
  }
}
