/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IStargateReceiver } from "./IStargateReceiver";
export type { IStargateRouter } from "./IStargateRouter";
export type { IStargateWidget } from "./IStargateWidget";
