/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IStargateWidget,
  IStargateWidgetInterface,
} from "../../../../contracts/interfaces/stargate/IStargateWidget";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes2",
        name: "_partnerId",
        type: "bytes2",
      },
    ],
    name: "partnerSwap",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IStargateWidget__factory {
  static readonly abi = _abi;
  static createInterface(): IStargateWidgetInterface {
    return new utils.Interface(_abi) as IStargateWidgetInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IStargateWidget {
    return new Contract(address, _abi, signerOrProvider) as IStargateWidget;
  }
}
